name: catalogoidera-stack  # << evita que tome el nombre de la carpeta
services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres16
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-coti}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-idera}
      POSTGRES_DB: ${POSTGRES_DB:-catalogoidera}
    ports:
      - "${POSTGRES_HOST_PORT:-5432}:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-coti} -d ${POSTGRES_DB:-catalogoidera}"]
      interval: 10s
      timeout: 5s
      retries: 5

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-admin@local.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin1234}
      PGADMIN_CONFIG_ALLOW_SPECIAL_EMAIL_DOMAINS: '["local"]'
      PGADMIN_CONFIG_CHECK_EMAIL_DELIVERABILITY: "False"
    ports:
      - "${PGADMIN_HOST_PORT:-8081}:80"      # << usa 8081 por defecto (evita conflicto 5050)
      # Si querés limitar a localhost:
      # - "127.0.0.1:${PGADMIN_HOST_PORT:-8081}:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  db-data:
  pgadmin-data:
